monolog:
    channels:
        - deprecation # Deprecations are logged in the dedicated "deprecation" channel when it exists

when@dev:
    monolog:
        handlers:
            main:
                type: stream
                path: '%kernel.logs_dir%/%kernel.environment%.log'
                level: debug
                channels: [ '!event' ]
            buffered:
                type: buffer
                handler: easylog
                level: debug
                channels: [ '!event' ]
            easylog:
                type: service
                id: easy_log.handler
            # Disabled for now see - https://github.com/symfony/symfony/pull/46475
            #firephp:
            #    type: firephp
            #    level: info
            chromephp:
                type: chromephp
                level: info
            console:
                type: console
                process_psr_3_messages: false
                channels: [ '!event', '!doctrine', '!console' ]

when@prod: &prod
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [ 404, 405 ]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: php://stderr
                level: debug
                formatter: monolog.formatter.json
            console:
                type: console
                process_psr_3_messages: false
                channels: [ '!event', '!doctrine' ]
            deprecation:
                type: stream
                channels: [ deprecation ]
                path: php://stderr
                formatter: monolog.formatter.json

when@staging: *prod

when@test:
    monolog:
        handlers:
            main:
                type: fingers_crossed
                action_level: error
                handler: nested
                excluded_http_codes: [ 404, 405 ]
                channels: [ '!event' ]
                buffer_size: 50 # How many messages should be saved? Prevent memory leaks
            nested:
                type: stream
                path: '%kernel.logs_dir%/%kernel.environment%.log'
                level: debug
            buffered:
                type: buffer
                handler: easylog
                level: error
                channels: [ '!event' ]
            easylog:
                type: service
                id: easy_log.handler
