version: '3.5'

services:

    symfony: &symfony-template
      image: ${COMPOSE_PROJECT_NAME}-symfony:latest
      build:
        context: .
        args:
          BUILD_ARGUMENT_ENV: dev
          HOST_UID: ${HOST_UID}
          HOST_GID: ${HOST_GID}
          XDEBUG_CONFIG: ${XDEBUG_CONFIG}
        dockerfile: ./Dockerfile
      container_name: ${COMPOSE_PROJECT_NAME}-symfony
      ports:
        - "${WEB_PORT_HTTP}:80"
        - "${WEB_PORT_SSL}:443"
      volumes:
        - ./:/var/www/html:cached
      depends_on:
        - mysql
        - rabbitmq
        - mail
      networks:
        - symfony

    ### Cron tasks, RabbitMQ consumers
    supervisord:
      <<: *symfony-template
      container_name: ${COMPOSE_PROJECT_NAME}-supervisord
      expose: []
      ports: []
      command: ["/usr/bin/supervisord"]

    mysql:
      image: mysql:${MYSQL_VERSION}
      platform: linux/x86_64
      container_name: ${COMPOSE_PROJECT_NAME}-mysql
      command: --innodb-use-native-aio=${INNODB_USE_NATIVE_AIO:-1} --sql_mode=${SQL_MODE:-"ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION"}
      environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: symfony
      ports:
        - "33061:3306"
      volumes:
        - ./var/mysql-data:/var/lib/mysql:delegated
        - ./docker/dev/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
      networks:
        - symfony

    rabbitmq:
      image: ${COMPOSE_PROJECT_NAME}-rabbitmq
      build:
        context: ./docker/rabbitmq/
        dockerfile: ./Dockerfile
      container_name: ${COMPOSE_PROJECT_NAME}-rabbitmq
      environment:
        RABBITMQ_ERLANG_COOKIE: 7ead507151fc4461b9f45c1161384a04
        RABBITMQ_DEFAULT_USER: guest
        RABBITMQ_DEFAULT_PASS: guest
        RABBITMQ_DEFAULT_VHOST: /
      ports:
        - "15672:15672"
      volumes:
        - ./var/rabbitmq:/var/lib/rabbitmq:delegated
      networks:
        - symfony

    mail:
      image: axllent/mailpit:latest
      container_name: ${COMPOSE_PROJECT_NAME}-mail
      restart: always
      ports:
        - "8025:8025"
        - "1025:1025"
      networks:
        - symfony

networks:
  symfony:
    name: symfony
